// Copyright (C) 2025 Cem Dervis
// This file is part of Polly.
// For conditions of distribution and use, see copyright notice in LICENSE.

#pragma once

#include "Polly/Algorithm.hpp"
#include "Polly/Any.hpp"
#include "Polly/Array.hpp"
#include "Polly/AudioDevice.hpp"
#include "Polly/BinaryReader.hpp"
#include "Polly/BlendState.hpp"
#include "Polly/ByteBlob.hpp"
#include "Polly/Camera.hpp"
#include "Polly/Color.hpp"
#include "Polly/Concepts.hpp"
#include "Polly/Defer.hpp"
#include "Polly/Degrees.hpp"
#include "Polly/Direction.hpp"
#include "Polly/Display.hpp"
#include "Polly/Error.hpp"
#include "Polly/Event.hpp"
#include "Polly/FileSystem.hpp"
#include "Polly/Font.hpp"
#include "Polly/Format.hpp"
#include "Polly/Function.hpp"
#include "Polly/Game.hpp"
#include "Polly/Gamepad.hpp"
#include "Polly/GamePerformanceStats.hpp"
#include "Polly/Image.hpp"
#include "Polly/ImGui.hpp"
#include "Polly/Input.hpp"
#include "Polly/Interval.hpp"
#include "Polly/Key.hpp"
#include "Polly/KeyModifier.hpp"
#include "Polly/Linalg.hpp"
#include "Polly/LinalgOps.hpp"
#include "Polly/Line.hpp"
#include "Polly/LinkedList.hpp"
#include "Polly/Logging.hpp"
#include "Polly/Math.hpp"
#include "Polly/Maybe.hpp"
#include "Polly/MeshVertex.hpp"
#include "Polly/MouseButton.hpp"
#include "Polly/MouseCursor.hpp"
#include "Polly/Narrow.hpp"
#include "Polly/NotNull.hpp"
#include "Polly/Painter.hpp"
#include "Polly/Pair.hpp"
#include "Polly/Particle.hpp"
#include "Polly/ParticleEmitter.hpp"
#include "Polly/ParticleModifier.hpp"
#include "Polly/ParticleSystem.hpp"
#include "Polly/PlatformInfo.hpp"
#include "Polly/Radians.hpp"
#include "Polly/Random.hpp"
#include "Polly/ReadableFile.hpp"
#include "Polly/Rectangle.hpp"
#include "Polly/RectPack.hpp"
#include "Polly/Sampler.hpp"
#include "Polly/Scancode.hpp"
#include "Polly/Seconds.hpp"
#include "Polly/Shader.hpp"
#include "Polly/SortedMap.hpp"
#include "Polly/SortedSet.hpp"
#include "Polly/Sound.hpp"
#include "Polly/SoundChannel.hpp"
#include "Polly/SoundTypes.hpp"
#include "Polly/Span.hpp"
#include "Polly/Spine.hpp"
#include "Polly/Sprite.hpp"
#include "Polly/String.hpp"
#include "Polly/StringView.hpp"
#include "Polly/Text.hpp"
#include "Polly/TextDecoration.hpp"
#include "Polly/ToString.hpp"
#include "Polly/Tween.hpp"
#include "Polly/UniquePtr.hpp"
#include "Polly/Util.hpp"
#include "Polly/Version.hpp"
#include "Polly/Window.hpp"
#include "Polly/WritableFile.hpp"

// We implicitly use the Polly namespace if the user includes this umbrella header, as intended.
using namespace Polly; // NOLINT(*-build-using-namespace)
